mutation SeedData @transaction @auth(level: USER, insecureReason: "This operation is safe to expose to all logged in users.") {
  user_insertMany(data: [
    {
      id: "550e8400-e29b-41d4-a716-446655440000",
      createdAt: "2024-04-26T12:00:00Z",
      email: "demouser1@example.com",
      passwordHash: "somehash1",
      role: "member"
    },
    {
      id: "550e8400-e29b-41d4-a716-446655440001",
      createdAt: "2024-04-26T13:00:00Z",
      email: "demouser2@example.com",
      passwordHash: "somehash2",
      role: "member"
    }
  ])
  location_insertMany(data: [
    {
      id: "650e8400-e29b-41d4-a716-446655440000",
      address: "123 Main St",
      createdAt: "2024-04-26T12:00:00Z",
      latitude: 34.0522,
      longitude: -118.2437,
      name: "Headquarters",
      radius: 50.0
    },
    {
      id: "650e8400-e29b-41d4-a716-446655440001",
      address: "456 Elm St",
      createdAt: "2024-04-26T13:00:00Z",
      latitude: 34.0523,
      longitude: -118.2438,
      name: "Branch Office",
      radius: 25.0
    }
  ])
  assignment_insertMany(data: [
    {
      userId: "550e8400-e29b-41d4-a716-446655440000",
      locationId: "650e8400-e29b-41d4-a716-446655440000",
      startDate: "2024-04-26",
    },
    {
      userId: "550e8400-e29b-41d4-a716-446655440001",
      locationId: "650e8400-e29b-41d4-a716-446655440001",
      startDate: "2024-04-27",
    }
  ])
}